config/routes.rb
Rails.application.routes.draw do
  
  resources :clients do
    
    resources :reports
    
    resources :users
  end
 
  root 'welcome#index'
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :reports, dependent: :destroy
  
  has_many :users, dependent: :destroy
  
  validates :name, presence: true,
                      length: { minimum: 3 }
  
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :client
  
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :client
  
  has_and_belongs_to_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  
  def index
    @clients = Client.all
  end
  
  def show
    @client = Client.find(params[:id])
  end
  
  def new
    @client = Client.new
  end
  
  def edit
    @client = Client.find(params[:id])
  end
  
  def create
    @client = Client.new(client_params)
 
    if @client.save
      redirect_to @client
    else
      render 'new'
    end
  end
  
  def update
    @client = Client.find(params[:id])
 
    if @client.update(client_params)
      redirect_to @client
    else
      render 'edit'
    end
  end
  
  def destroy
    @client = Client.find(params[:id])
    @client.destroy
 
    redirect_to clients_path
  end
  
  def upload
    uploaded_io = params[:client][:attachment]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'w') do |file|
    file.write(uploaded_io.read)
    end
  end
 
  private
    def client_params
      params.require(:client).permit(:name, :logo, :attachment)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def index
    @reports = Report.all
  end
  
  def new
    @client = Client.find(params[:client_id])
    @report = Report.new
  end
  
  def create
    @client = Client.find(params[:client_id])
    @report = @client.reports.create(report_params)
    redirect_to client_path(@client)
  end
    
  def destroy
    @client = Client.find(params[:client_id])
    @report = @client.reports.find(params[:id])
    @report.destroy
    redirect_to client_path(@client)
  end
 
  private
    def report_params
      params.require(:report).permit(:commenter, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  
  def index
    @users = User.all
  end
  
  def new
    @client = Client.find(params[:client_id])
    @user = User.new
  end
  
  def create
    @client = Client.find(params[:client_id])
    @user = @client.users.create(user_params)
    redirect_to client_path(@client)
  end
    
  def destroy
    @client = Client.find(params[:client_id])
    @user = @client.users.find(params[:id])
    @user.destroy
    redirect_to client_path(@client)
  end
 
  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.slim
.row
  .col-md-4
    = form_for @client do |f|
 
      - if @client.errors.any?
        #error_explanation.bg-warning
          p
            = pluralize(@client.errors.count, "error") 
            | prohibited this client from being saved:
      
          ul
            - @client.errors.full_messages.each do |msg|
              li = msg
      .form-group
        = f.label :client_name
        br
        = f.text_field :name, class: 'form-control'
  
      .form-group
        = f.label :upload_logo
        br
        = f.text_field :logo, class: 'form-control'
      
      .form-group  
        = f.label :attachment
        br
        = f.file_field :attachment, class: 'form-control'
  
      .form-group
        button.btn.btn-default type="submit" Submit

app/views/clients/edit.html.slim
h1 Editing client
 
= render 'form'
 
= link_to 'Back', clients_path

app/views/clients/index.html.slim
h2 Your Clients

= link_to 'New Clients', new_client_path, :class => 'btn btn-primary'

br
br
.row
  .col-md-12
    table.table.table-striped
      thead
        tr
          th Clients
          th Reports
          th Users
          th Last Updated
          th Edit
          th Delete
      
      tbody
        - @clients.each do |client|
          tr
            td = link_to client.name, client_path(client)
            td = link_to client.reports.size, client_reports_path(client)
            td = link_to client.users.size, client_users_path(client)
            td = client.updated_at
            td = link_to '', edit_client_path(client), :class => 'glyphicon glyphicon-edit'
            td = link_to '', client_path(client), :class => 'glyphicon glyphicon-trash',
                  method: :delete,
                  data: { confirm: 'Are you sure?' }

app/views/clients/new.html.slim
h1 New Client

= render 'form'
    
= link_to 'Back', clients_path

app/views/clients/show.html.slim
h2 = @client.name
 
p = @client.logo

p
  = link_to 'Edit', edit_client_path(@client), :class => 'btn btn-default'
  = link_to 'Back', clients_path, :class => 'btn btn-default'
br

h4 Reports hello
p = link_to 'New Reports', new_client_report_path(@client), :class => 'btn btn-primary'
table.table.table-striped
  thead
    tr 
      th Report Title:
      th Report Body:
      th Edit
      th Delete
  tbody
    = render @client.reports
br
br

h4 Users
p = link_to 'New Users', new_client_user_path(@client), :class => 'btn btn-primary'
table.table.table-striped
  thead
    tr 
      th User Name:
      th Email:
      th Edit
      th Delete
    tbody 
      = render @client.users
  


/ = render 'reports/form'
/
/ h2 Add a user
/ = render 'users/form'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Doublecheck
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body data-no-turbolink=""

    .container-fluid#container
      h1 Doublecheck Logo

      = yield

app/views/reports/_form.html.slim
.row
  .col-md-4
    = form_for([@client, @client.reports.build]) do |f| 
      .form-group
        = f.label :title 
        br
        = f.text_field :commenter, class: 'form-control'
  
      .form-group
        = f.label :body
        br
        = f.text_area :body, class: 'form-control'
  
      .form-group
        button.btn.btn-default type="submit" Submit

app/views/reports/_report.html.slim
tr
  td = report.commenter
  td = report.body
  td = link_to '', '', :class => 'glyphicon glyphicon-edit'
  td 
    = link_to '', [report.client, report], :class => 'glyphicon glyphicon-trash',
        method: :delete,
        data: { confirm: 'Are you sure?' }

app/views/reports/new.html.slim
h1 New Report

= render 'form'

= link_to 'Back', client_path(@client), :class => 'btn btn-default'

app/views/shared/_global.html.slim
ul.list-inline
  li
    = link_to 'Clients', clients_path, :class => 'btn btn-primary'
  li
    = link_to 'Reports', 'www.google.com', :class => 'btn btn-primary'

app/views/users/_form.html.slim
.row
  .col-md-4
    = form_for([@client, @client.users.build]) do |f| 
      .form-group
        = f.label :user_name 
        br
        = f.text_field :name, class: 'form-control'
  
      .form-group
        = f.label :email
        br
        = f.text_field :email, class: 'form-control'
      
      .form-group
        = f.label :reports
        br
        = select_tag "reporting_list", options_from_collection_for_select(Report.all, 'id', 'name',@user.reports.map{ |j| j.id }), :multiple => true
  
      .form-group
        button.btn.btn-default type="submit" Submit

app/views/users/_user.html.slim
tr
  td = user.name
  td = user.email
  td = link_to '', '', :class => 'glyphicon glyphicon-edit'
  td = link_to '', [user.client, user], :class => 'glyphicon glyphicon-trash',
            method: :delete,
            data: { confirm: 'Are you sure?' }

app/views/users/edit.html.slim
h1 Editing client
 
= render 'form'

= link_to 'Back', client_path(@client), :class => 'btn btn-default'

app/views/users/index.html.slim
h2 Users
  
table.table.table-striped
  thead
    tr 
      th Report Title:
      th Report Body:
      th Edit
      th Delete
  tbody
  - @users.each do |user|
    tr
      td = user.name
      td = user.email
      td edit
      td delete

app/views/users/new.html.slim
h1 New Users

= render 'form'

= link_to 'Back', client_path(@client), :class => 'btn btn-default'

app/views/welcome/index.html.slim
= render 'shared/global'